 const String APP_USER="USER";
 const String APP_ADMIN="ADMIN";
 const String PROFILE_PIC_STORAGE_BUCKET="PROFILE_PIC";
 const String WALLPAPERS_STORAGE_BUCKET="WALLPAPERS";
 const String USERS_COLLECTION="USERS";
 const String NATURE_WALLPAPER_COLLECTION="NATURE_WALLPAPER";
 const String WALLPAPERS_COLLECTION="WALLPAPERS";